### PR TITLE
Update used packages to latest versions to make the repo working on mac m1 && update to Python 3.8 and ubuntu-latest in Python CI

### PR DESCRIPTION
**Pull request by grimmerk**
## Types of changes

- **Bugfix**: #46 

Tested cases:
-  python 3.9.2 on m1: ok
-  python 3.8.8, 3.9.2 on intel: ok
-  python 3.7.10 on intel: `No module named 'google.cloud'` <- need figure out why. ( in `from google.cloud import bigquery`) 

master branch:
- python 3.7.10 on intel: VSCode works but terminal shows `ModuleNotFoundError: No module named 'google'` ( in `from google.cloud import bigquery`) 

NOTE: Upgrading to 3.8 is included in this PR to solve above issue

### CODE REVIEW

**Comment by tai271828** [comment]
Ubuntu-mate 18.04 looks good to build this codebase with poetry from scratch. Python version 3.7.5.

How I tested:
```
$ git clone git@github.com:pycontw/pycon-etl.git -b update_packages_compatible_on_m1
$ cd pycon-etl
$ poetry shell
$ poetry install
```

**Comment by tai271828** [comment]
I can reproduce the test case failure:

```
$ make test
poetry run pytest
================================================ test session starts ================================================
platform linux -- Python 3.7.5, pytest-5.4.3, py-1.10.0, pluggy-0.13.1
rootdir: /home/tai271828/work-my-projects/pycontw-projects/tmp-test/pycon-etl
plugins: cov-2.12.1, anyio-3.3.0
collected 1 item / 1 error                                                                                          

====================================================== ERRORS =======================================================
________________________________ ERROR collecting tests/test_cakeresume_uploader.py _________________________________
ImportError while importing test module '/home/tai271828/work-my-projects/pycontw-projects/tmp-test/pycon-etl/tests/test_cakeresume_uploader.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_cakeresume_uploader.py:4: in <module>
    from contrib.survey_cake.udfs.survey_cake_csv_uploader import SurveyCakeCSVUploader
contrib/survey_cake/udfs/survey_cake_csv_uploader.py:5: in <module>
    from google.cloud import bigquery
E   ModuleNotFoundError: No module named 'google.cloud'
============================================== short test summary info ==============================================
ERROR tests/test_cakeresume_uploader.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================================= 1 error in 0.10s ==================================================
Makefile:14: recipe for target 'test' failed
make: *** [test] Error 2
```

> Ubuntu-mate 18.04 looks good to build this codebase with poetry from scratch. Python version 3.7.5.
> 
> How I tested:
> 
> ```
> $ git clone git@github.com:pycontw/pycon-etl.git -b update_packages_compatible_on_m1
> $ cd pycon-etl
> $ poetry shell
> $ poetry install
> ```

**Comment by tai271828** [comment]
By invoking `pip install google-cloud-bigquery` we can resolve the `E   ModuleNotFoundError: No module named 'google.cloud'` issue. It seems that `poetry` does not install `google-cloud-bigquery` initially.

**Comment by grimmer0125** [comment]
@tai271828 could you checkout to `master` and try the same procedures you have done (e.g. make test) and see the result? 
I thought using your same environment to test again can help excluding some factors.

**Comment by tai271828** [comment]
Build from scratch with `master` looks good: 1) `google-cloud-bigquery` 2.6.1 is installed 2) `make test` passes (with `.env.sh` setup correctly).

> @tai271828 could you checkout to `master` (even from fresh clone) and try the same procedures you have done (e.g. make test) and see the result?
> I thought using your same environment to test again can help excluding some factors.

**Review by david30907d — APPROVED** [review]
utACK

**Pull request merged**
